config/routes.rb
Rails.application.routes.draw do

  resources :tuberculoses

  resources :tuberculosis

  get 'reporte/index'
  get 'reporte/pacientes'
  get 'reporte/detalle_insumos_reactivos'
  get 'reporte/insumo_reactivos_pacientes'
  get 'reporte/hospital'

  resources :laboratorios

  resources :personas

  resources :comunidads

  resources :municipios

  resources :line_items

  resources :carts

  get 'registro_insumos_reactivos/index2'

  resources :registro_insumos_reactivos

  resources :baciloscopia_forms

  resources :form_cultivos

  get 'configuraciones/index'

  resources :establecimientos

  resources :sectors

  resources :areas

  resources :distritos

  resources :provincia

  resources :kardexes

  resources :insumo_reactivos

  resources :inventarios

  resources :form_leishmaniases

  resources :form_malaria

  resources :form_chagas

  resources :form_tuberculoses

  resources :form_liquidos

  resources :biopsias_forms

  resources :form_anat_citologicas

  resources :form_cancer_uterinos

  resources :form_laboratorios

  resources :hospitals

  resources :diagnosticos

  resources :pacientes

  resources :rols

  get 'principal/index'

  devise_for :users
  resources :users

  root 'principal#index'

end

app/models/form_cancer_uterino.rb
class FormCancerUterino < ActiveRecord::Base
  belongs_to :paciente
  belongs_to :hospital
  belongs_to :distrito

  #has_many :paciente

  validates :paciente, uniqueness: {case_sensitive: false ,message: "ya esta registrado"}
  validates_numericality_of :edad_menarquia
  validates_presence_of :fecha_ult_menstruacion

  validates :nivel_social, inclusion: {in: (1..5)}
  NIVELSOCIAL = ['1', '2', '3', '4', '5']
  validates :n_emabarazos, inclusion: {in: (1..25)}
  EMBARAZOS = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25']
  validates :aspecto_cuello, inclusion: {in: ['Sano', 'Benigno', 'Atrófico', 'Sospechoso de neoplasia', 'Ectropion']}
  ASPECTO = ['Sano', 'Benigno', 'Atrófico', 'Sospechoso de neoplasia', 'Ectropion']
  validates :flujo_vaginal, inclusion: {in: ['Sin Flujo', 'Con Flujo']}
  FLUJO = ['Sin Flujo', 'Con Flujo']
  validates :lugar_de_muestra, inclusion: {in: ['Menorragia', 'Sinurragia Endocervical', 'Ninguno Exocervical', 'Endometrial', 'Otro Schiller']}
  LUGAR = ['Menorragia', 'Sinurragia Endocervical', 'Ninguno Exocervical', 'Endometrial', 'Otro Schiller']
  validates :tratamiento, inclusion: {in: ['Sin tratamiento', 'Dia termo', 'Criocirug. hormonal conizacion']}
  Tratamiento = ['Sin tratamiento', 'Dia termo', 'Criocirug. hormonal conizacion']
  validates :planificacion_familiar, inclusion: {in: ['No', 'Ritmo', 'DIU', 'Ligadura de trompas', 'Oral', 'Depo', 'Otros']}
  PLANIFICACION = ['No', 'Ritmo', 'DIU', 'Ligadura de trompas', 'Oral', 'Depo', 'Otros']
  validates :n_abortos, inclusion: {in: (1..24)}
  ABORTOS = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24']

  NUMEROS = /\A[0-9]+\z/
  validates :edad_menarquia, format: { :with => NUMEROS , message: "Ingrese solo numeros positivos" }
  validates :n_cesareas, format: { :with => NUMEROS , message: "Ingrese solo numeros positivos" }



end

app/controllers/form_cancer_uterinos_controller.rb
class FormCancerUterinosController < ApplicationController
  before_action :set_form_cancer_uterino, only: [:show, :edit, :update, :destroy]

  # GET /form_cancer_uterinos
  # GET /form_cancer_uterinos.json
  def index
    @form_cancer_uterinos = FormCancerUterino.all
    query = queryGrafico('form_cancer_uterinos')
    #query = "SELECT date_trunc('month', created_at) as label, COUNT(*) AS value  FROM form_chagas where form_chagas.created_at>='2016-01-01 00:00:00' and form_chagas.created_at<='2016-12-12 24:00:00' GROUP BY 1 ORDER BY label ASC"
    @reporte_mensual_cancer = Paciente.find_by_sql(query)
    gon.query = query
    gon.reporte_mensual_cancer = @reporte_mensual_cancer
  end

  # GET /form_cancer_uterinos/1
  # GET /form_cancer_uterinos/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "file_name",
               :layout => 'pdf.html.erb',
               :page_size => 'Letter',
               :footer => {:right => '[page] de [topage]', :font_size => 7}
      end
    end
  end

  # GET /form_cancer_uterinos/new
  def new
    @form_cancer_uterino = FormCancerUterino.new
  end

  # GET /form_cancer_uterinos/1/edit
  def edit
  end

  # POST /form_cancer_uterinos
  # POST /form_cancer_uterinos.json
  def create
    @form_cancer_uterino = FormCancerUterino.new(form_cancer_uterino_params)
    begin
      @paciente = Paciente.find(params[:form_cancer_uterino][:paciente_id])  
    rescue Exception => e
      @paciente = Paciente.find(6)
    end
    
    @paciente.form_laboratorio_id=12
    @paciente.save

    fecha_ult_menstruacion = params[:form_cancer_uterino][:fecha_ult_menstruacion]
    fecha_ult_parto = params[:form_cancer_uterino][:fecha_ult_parto]
    fecha_aborto = params[:form_cancer_uterino][:fecha_aborto]


    respond_to do |format|
      if @form_cancer_uterino.save
        format.html { redirect_to @form_cancer_uterino, notice: 'Form cancer uterino was successfully created.' }
        format.json { render :show, status: :created, location: @form_cancer_uterino }
      else
        format.html { render :new }
        format.json { render json: @form_cancer_uterino.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_cancer_uterinos/1
  # PATCH/PUT /form_cancer_uterinos/1.json
  def update
    respond_to do |format|
      if @form_cancer_uterino.update(form_cancer_uterino_params)
        format.html { redirect_to @form_cancer_uterino, notice: 'Form cancer uterino was successfully updated.' }
        format.json { render :show, status: :ok, location: @form_cancer_uterino }
      else
        format.html { render :edit }
        format.json { render json: @form_cancer_uterino.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_cancer_uterinos/1
  # DELETE /form_cancer_uterinos/1.json
  def destroy
    @form_cancer_uterino.destroy
    respond_to do |format|
      format.html { redirect_to form_cancer_uterinos_url, notice: 'Form cancer uterino was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_form_cancer_uterino
    @form_cancer_uterino = FormCancerUterino.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def form_cancer_uterino_params
    params.require(:form_cancer_uterino).permit(:paciente_id, :hospital_id, :edad_menarquia, :fecha_ult_menstruacion, :fecha_ult_parto, :fecha_aborto, :nivel_social, :n_emabarazos, :n_abortos, :n_cesareas, :estado_lactancia, :menopausia, :embarazo, :planificacion_familiar, :tratamiento, :ligadura_trompas, :aspecto_cuello, :flujo_vaginal, :lugar_de_muestra, :informacion_toma_muestra, :control, :fecha_entrega, :distrito_id)
  end
end

app/helpers/form_cancer_uterinos_helper.rb
module FormCancerUterinosHelper
end

app/views/form_cancer_uterinos/edit.html.erb
<h1>Editar Formulario Cancer Uterino</h1>

<%= render 'form' %>

<%= link_to 'Ver', @form_cancer_uterino %> |
<%= link_to 'Atras', form_cancer_uterinos_path %>

app/views/form_cancer_uterinos/index.html.erb
<h1>Cancer de Cuello Uterino</h1>

<table class="table table-striped table-hover" id="exportPDF" id="exportPDF">
  <thead>
  <tr>
    <th>Paciente</th>
    <th>Hospital</th>
    <th>Distrito</th>
    <th>Edad de Menarquia</th>
    <th>Fecha de la Ultima Menstruacion</th>
    <th>Fecha Ultimo Parto</th>
    <th>Fecha Aborto</th>
    <th>Nivel Social</th>
    <th>Nro de Embarazos</th>
    <th>Nro de Abortos</th>
    <th>Nro de Cesareas</th>
    <th>Estado  de Lactancia</th>
    <th>Menopausia</th>
    <th>Embarazo</th>
    <th>Planificacion familiar</th>
    <th>Tratamiento</th>
    <th>Aspecto cuello</th>
    <th>Flujo vaginal</th>
    <th>Lugar de muestra</th>
    <th>Informacion durante la Toma de Muestra</th>
    <th>Control</th>
    <th>Fecha Entrega Pap</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @form_cancer_uterinos.each do |form_cancer_uterino| %>
      <tr>
        <td><%= form_cancer_uterino.paciente.nombres %></td>
        <td><%= form_cancer_uterino.hospital %></td>
        <td><%= form_cancer_uterino.distrito %></td>
        <td><%= form_cancer_uterino.fecha_ult_menstruacion %></td>
        <td><%= form_cancer_uterino.fecha_ult_parto %></td>
        <td><%= form_cancer_uterino.fecha_aborto %></td>
        <td><%= form_cancer_uterino.nivel_social %></td>
        <td><%= form_cancer_uterino.n_emabarazos %></td>
        <td><%= form_cancer_uterino.n_abortos %></td>
        <td><%= form_cancer_uterino.n_cesareas %></td>
        <td><%= form_cancer_uterino.estado_lactancia %></td>
        <td><%= form_cancer_uterino.menopausia %></td>
        <td><%= form_cancer_uterino.embarazo %></td>
        <td><%= form_cancer_uterino.tratamiento %></td>
        <td><%= form_cancer_uterino.planificacion_familiar %></td>
        <td><%= form_cancer_uterino.aspecto_cuello %></td>
        <td><%= form_cancer_uterino.flujo_vaginal %></td>
        <td><%= form_cancer_uterino.lugar_de_muestra %></td>
        <td><%= form_cancer_uterino.informacion_toma_muestra %></td>
        <td><%= form_cancer_uterino.control %></td>
        <td><%= form_cancer_uterino.fecha_entrega %></td>
        <td><%= link_to 'Ver', form_cancer_uterino %></td>
        <td><%= link_to 'Editar', edit_form_cancer_uterino_path(form_cancer_uterino) %></td>
        <td><%= link_to 'Eliminar', form_cancer_uterino, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <td>
          <%= link_to '<i class="glyphicon glyphicon-list-alt"></i>'.html_safe, {:format => "pdf", :controller => "form_cancer_uterinos", action: "show", :id => form_cancer_uterino}, :"data-toggle" => "tooltip", :"data-placement" => "bottom", :title => "Crear  Informe", :target => "_blank" %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Cancer Uterino', new_form_cancer_uterino_path, :class=> "btn" %>

<a href="javascript:location.reload()">Mostrar historial de registro</a>

<script type="text/javascript">
   var table12_Props = {
    highlight_keywords: true,
    on_keyup: true,
    on_keyup_delay: 1500,
    single_search_filter: true,
    selectable: true
};
var tf12 = setFilterGrid("exportPDF", table12_Props);

</script>

<script src="tablefilter.js"></script>
<script src="tablefilter_all_min.js"></script>
<script src="ezEditTable.js"></script>
<script type="text/javascript">
  function demoFromHTML1() {
    var pdf = new jsPDF('p', 'pt', 'letter');

    pdf.cellInitialize();
    pdf.setFontSize(10);
    $.each( $('#exportPDF tr'), function (i, row){
        $.each( $(row).find("td, th"), function(j, cell){
            var txt = $(cell).text().trim()+"adad" || " ";
            var width = (j==4) ? 40 : 70; //make 4th column smaller
            console.log("fghjklñ");
            console.log($(cell));
            pdf.cell(10, 50, width, 30, txt, i);
        });
    });

    pdf.save('sample-file.pdf');
}
</script>

<div id="chart-container"></div>
<script type="text/javascript">
  console.log(gon.query);
</script>
<script type="text/javascript">
  FusionCharts.ready(grafico_columna("chart-container","Historial de registro del ultimo año Cultivos","Meses","Cantidad de pacientes registrados",gon.reporte_mensual_cancer));
</script>
<script type="text/javascript">
    console.log(gon.datos)
</script>

app/views/form_cancer_uterinos/new.html.erb
<h1>Nuevo Cancer Uterino</h1>

<%= render 'form' %>

<%= link_to 'Atras', form_cancer_uterinos_path %>

app/views/form_cancer_uterinos/show.html.erb
<div class="pull-left" style="width: 10%;display: inline-block">
  <%= image_tag "bolivia_escudo.png", :width => '75' %>
</div>
<div style="width: 70%;;display: inline-block" class="text-center">
  <strong>
    SOLICITUD DE ANALISIS PAP<br/>
    MINISTERIO DE SALUD Y DEPORTES<br/>
    HONORABLE GOBIERNO MUNICIPAL DE POTOSI<br/>
    SERVICIO DEPARTAMENTAL DE SALUD<br/>
    PROGRAMA NACIONAL DE SCREENING DE CANCER DE CUELLO UTERNINO<br/>
  </strong>
</div>
<div class="pull-right" style="width: 15%;;display: inline-block">
  <%= image_tag "potosi_escudo.gif", :width => '50' %>
</div>

<table class="table table-condensed">
  <tbody>
  <tr>
    <td><strong>CENTRO DE SALUD:</strong> <%= @form_cancer_uterino.hospital %></td>
    <td colspan="2"><strong>DISTRITO:</strong> <%= @form_cancer_uterino.distrito %></td>

  </tr>
  <tr>
    <td><strong>AREA:</strong> <%= @form_cancer_uterino.hospital.establecimiento %></td>
    <td colspan="2"><strong>No DE REGISTRO:</strong> <%= @form_cancer_uterino.id %></td>
  </tr>
  </tbody>
</table>

<h5><b>DATOS DEL PACIENTE</b></h5>
<table class="table table-condensed">
  <tbody>
  <tr>
    <td colspan="3"><strong>NOMBREs:</strong> <%= @form_cancer_uterino.paciente %></td>
  </tr>
  <tr>
    <td><strong>DIRECCION:</strong> <%= @form_cancer_uterino.paciente.direccion %></td>
    <td><strong>Fecha de Nacimiento:</strong> <%= @form_cancer_uterino.paciente.fecha_nacimiento %></td>
    <td><strong>EDAD:</strong> <%= Paciente.calcular_edad(@form_cancer_uterino.paciente.fecha_nacimiento).to_s %></td>
  </tr>

  <tr>
    <td colspan="3"><strong>EDAD MENARQUIA:</strong>  <%= @form_cancer_uterino.edad_menarquia %></td>
  </tr>
  <tr>
    <td colspan="3"><strong>FECHA DE LA TOMA DE MUESTRA:</strong>  <%= @form_cancer_uterino.paciente %></td>
  </tr>
  <tr>
    <td colspan="3"><strong>FECHA ULTIMA MENSTRUAL:</strong>  <%= @form_cancer_uterino.fecha_ult_menstruacion %></td>
  </tr>
  <tr>
    <td colspan="3"><strong>FECHA ULTIMO PARTO:</strong>  <%= @form_cancer_uterino.fecha_ult_parto %></td>
  </tr>
  <tr>
    <td colspan="3"><strong>FECHA DE ABORTO:</strong>  <%= @form_cancer_uterino.fecha_aborto %></td>
  </tr>
  <tr>
    <td colspan="3"><strong>NIVEL SOCIAL:</strong>  <%= @form_cancer_uterino.nivel_social %></td>
  </tr>
  </tbody>
</table>

<table class="table table-condensed">
  <tr>
    <td>
      <strong>DATOS GINECOLOGICOS</strong><br/>
      <p>
        <strong>Nro de Embarazos:</strong>
        <%= @form_cancer_uterino.n_emabarazos %>
      </p>
      <strong>RADIOTERAPIA</strong><br/>
      <p>
        <strong>Nro Abortos:</strong>
        <%= @form_cancer_uterino.n_abortos %>
      </p>
      <strong>
        HISTERECTOMIA
      </strong><br/>

      <p>
        <strong>Nro de Cesareas:</strong>
        <%= @form_cancer_uterino.n_cesareas %>
      </p>

      <p>
        <strong>Estado de Lactancia:</strong>
        <%= @form_cancer_uterino.estado_lactancia ? 'SI' : 'NO' %>
      </p>

      <p>
        <strong>Menopausia:</strong>
        <%= @form_cancer_uterino.menopausia ? 'SI' : 'NO' %>
      </p>

      <p>
        <strong>Embarazo:</strong>
        <%= @form_cancer_uterino.embarazo ? 'SI' : 'NO' %>
      </p>

    </td>
    <td><p>
      <strong>PLANIFICACION FAMILIAR</strong><br/>
      <%= @form_cancer_uterino.planificacion_familiar %>
    </p>
    </td>
    <td><p>
      <strong>TRATAMIENTO</strong><br/>
      <%= @form_cancer_uterino.tratamiento %>
    </p></td>
  </tr>
</table>

<table class="table table-condensed">
  <tr>
    <td><p>
      <strong>ASPECTO DEL CUELLO</strong><br/>
      <%= @form_cancer_uterino.aspecto_cuello %>
    </p></td>
    <td><p>
      <strong>FLUJO VAGINAL</strong><br/>
      <%= @form_cancer_uterino.flujo_vaginal %>
    </p>
    </td>
    <td><p>
      <strong>LUGAR DE MUESTRA</strong><br/>
      <%= @form_cancer_uterino.lugar_de_muestra %>
    </p></td>
  </tr>
</table>

<p>
  <strong>1. Informacion durante la toma muestra?</strong><br/>
  <%= @form_cancer_uterino.informacion_toma_muestra %>
</p>

<p>
  <strong>2. Control:</strong>
  <%= @form_cancer_uterino.control ? 'Si' : 'No' %>
</p>

<p>
  <strong>3. Resultado ultimo "PAP"y Fecha</strong>
  <%= @form_cancer_uterino.fecha_entrega %>
</p>

<p>
  <strong>4. Responsable de la forma de muestra nombre, apellido y sello</strong>
</p>

<p>
  <strong>NOTA.-</strong>La informacion qe anote sera de capital importancia para la paciente Gracias!
</p>

<%= link_to 'Editar', edit_form_cancer_uterino_path(@form_cancer_uterino) %> |
<%= link_to 'Atras', form_cancer_uterinos_path %>

<script type="text/javascript">
console.log("adsljfldsjfdsjf");
    console.log(gon.datos);
    console.log(gon.d2);
</script>

app/views/form_cancer_uterinos/show.pdf.erb
<br>
<br>
<div class="pull-left" style="width: 10%;display: inline-block">
  <%= wicked_pdf_image_tag "bolivia_escudo.png", :width => '75' %>
</div>
<div style="width: 70%;;display: inline-block" class="text-center">

  <strong>
    SOLICITUD DE ANALISIS PAP<br/>
    MINISTERIO DE SALUD Y DEPORTES<br/>
    HONORABLE GOBIERNO MUNICIPAL DE POTOSI<br/>
    SERVICIO DEPARTAMENTAL DE SALUD<br/>
    PROGRAMA NACIONAL DE SCREENING DE CANCER DE CUELLO UTERNINO<br/>
  </strong>

</div>
<div class="pull-right" style="width: 10%;;display: inline-block">
  <%= wicked_pdf_image_tag "potosi_escudo.gif", :width => '50' %>
</div>
<table class="table table-condensed">
  <tbody>
  <tr>
    <td><strong>CENTRO DE SALUD:</strong> <%= @form_cancer_uterino.hospital %></td>
    <td><strong>DISTRITO:</strong> <%= @form_cancer_uterino.hospital.distrito %></td>
    <td><strong>AREA:</strong> <%= @form_cancer_uterino.hospital.establecimiento %></td>
  </tr>
  <tr>
    <td><strong>SECTOR:</strong> <%= @form_cancer_uterino.hospital.centro_salud %></td>
    <td colspan="2"><strong>No DE REGISTRO:</strong> <%= @form_cancer_uterino.id %></td>
  </tr>
  </tbody>

</table>

<h5><b>DATOS DEL PACIENTE</b></h5>
<table class="table table-condensed">
  <tbody>
  <tr>
    <td colspan="3"><strong>NOMBRE:</strong> <%= @form_cancer_uterino.paciente.nombres %><%= " " %><%= @form_cancer_uterino.paciente.apellidos %></td>
  </tr>
  <tr>
    <td><strong>DIRECCION:</strong> <%= @form_cancer_uterino.paciente.direccion %></td>
    <td><strong>Fecha de Nacimiento:</strong> <%= @form_cancer_uterino.paciente.fecha_nacimiento %></td>
    <td><strong>EDAD:</strong> <%= Paciente.calcular_edad(@form_cancer_uterino.paciente.fecha_nacimiento).to_s %></td>
  </tr>

  <tr>
    <td colspan="3"><strong>EDAD MENARQUIA:</strong>  <%= @form_cancer_uterino.edad_menarquia %></td>
  </tr>
  <tr>
    <td colspan="3"><strong>FECHA DE LA TOMA DE MUESTRA:</strong>  <%= @form_cancer_uterino.paciente.created_at %></td>
  </tr>
  <tr>
    <td colspan="3"><strong>FECHA ULTIMA MENSTRUAL:</strong>  <%= @form_cancer_uterino.fecha_ult_menstruacion %></td>
  </tr>
  <tr>
    <td colspan="3"><strong>FECHA ULTIMO PARTO:</strong>  <%= @form_cancer_uterino.fecha_ult_parto %></td>
  </tr>
  <tr>
    <td colspan="3"><strong>FECHA DE ABORTO:</strong>  <%= @form_cancer_uterino.fecha_aborto %></td>
  </tr>
  <tr>
    <td colspan="3"><strong>NIVEL SOCIAL:</strong>  <%= @form_cancer_uterino.nivel_social %></td>
  </tr>
  </tbody>

</table>

<table class="table table-condensed">
  <tr>
    <td>
      <strong>DATOS GINECOLOGICOS</strong><br/>

      <p>
        <strong>Nro de Embarazos:</strong>
        <%= @form_cancer_uterino.n_emabarazos %>
      </p>
      <strong>RADIOTERAPIA</strong><br/>

      <p>
        <strong>Nro Abortos:</strong>
        <%= @form_cancer_uterino.n_abortos %>
      </p>
      <strong>
        HISTERECTOMIA
      </strong><br/>

      <p>
        <strong>Nro de Cesareas:</strong>
        <%= @form_cancer_uterino.n_cesareas %>
      </p>

      <p>
        <strong>Estado de Lactancia:</strong>
        <%= @form_cancer_uterino.estado_lactancia ? 'SI' : 'NO' %>
      </p>

      <p>
        <strong>Menopausia:</strong>
        <%= @form_cancer_uterino.menopausia ? 'SI' : 'NO' %>
      </p>

      <p>
        <strong>Embarazo:</strong>
        <%= @form_cancer_uterino.embarazo ? 'SI' : 'NO' %>
      </p>

    </td>
    <td><p>
      <strong>PLANIFICACION FAMILIAR</strong><br/>
      <%= @form_cancer_uterino.planificacion_familiar %>
    </p>
    </td>
    <td><p>
      <strong>TRATAMIENTO</strong><br/>
      <%= @form_cancer_uterino.tratamiento %>
    </p></td>
  </tr>
</table>

<table class="table table-condensed">
  <tr>
    <td><p>
      <strong>ASPECTO DEL CUELLO</strong><br/>
      <%= @form_cancer_uterino.aspecto_cuello %>
    </p></td>
    <td><p>
      <strong>FLUJO VAGINAL</strong><br/>
      <%= @form_cancer_uterino.flujo_vaginal %>
    </p>
    </td>
    <td><p>
      <strong>LUGAR DE MUESTRA</strong><br/>
      <%= @form_cancer_uterino.lugar_de_muestra %>
    </p></td>
  </tr>
</table>

<p>
  <strong>1. Informacion durante la toma muestra?</strong><br/>
  <%= @form_cancer_uterino.informacion_toma_muestra %>
</p>

<p>
  <strong>2. Control:</strong>
  <%= @form_cancer_uterino.control ? 'Si' : 'No' %>
</p>

<p>
  <strong>3. Resultado ultimo "PAP"y Fecha</strong>
  <%= @form_cancer_uterino.fecha_entrega %>
</p>

<p>
  <strong>4. Responsable de la forma de muestra nombre, apellido y sello</strong>
</p>

<p>
  <strong>NOTA.-</strong>La informacion qe anote sera de capital importancia para la paciente Gracias!
</p>