config/routes.rb
Rails.application.routes.draw do

  resources :tuberculoses

  resources :tuberculosis

  get 'reporte/index'
  get 'reporte/pacientes'
  get 'reporte/detalle_insumos_reactivos'
  get 'reporte/insumo_reactivos_pacientes'
  get 'reporte/hospital'

  resources :laboratorios

  resources :personas

  resources :comunidads

  resources :municipios

  resources :line_items

  resources :carts

  get 'registro_insumos_reactivos/index2'

  resources :registro_insumos_reactivos

  resources :baciloscopia_forms

  resources :form_cultivos

  get 'configuraciones/index'

  resources :establecimientos

  resources :sectors

  resources :areas

  resources :distritos

  resources :provincia

  resources :kardexes

  resources :insumo_reactivos

  resources :inventarios

  resources :form_leishmaniases

  resources :form_malaria

  resources :form_chagas

  resources :form_tuberculoses

  resources :form_liquidos

  resources :biopsias_forms

  resources :form_anat_citologicas

  resources :form_cancer_uterinos

  resources :form_laboratorios

  resources :hospitals

  resources :diagnosticos

  resources :pacientes

  resources :rols

  get 'principal/index'

  devise_for :users
  resources :users

  root 'principal#index'

end

app/models/form_laboratorio.rb
class FormLaboratorio < ActiveRecord::Base
  belongs_to :paciente
  belongs_to :usuario
  belongs_to :hospital

  has_many :inventarios
  has_many :insumo_reactivos

  def to_s
    "#{nombre}"
  end

end

app/controllers/form_laboratorios_controller.rb
class FormLaboratoriosController < ApplicationController
  before_action :set_form_laboratorio, only: [:show, :edit, :update, :destroy]

  # GET /form_laboratorios
  # GET /form_laboratorios.json
  def index
    @form_laboratorios = FormLaboratorio.all
  end

  # GET /form_laboratorios/1
  # GET /form_laboratorios/1.json
  def show
  end

  # GET /form_laboratorios/new
  def new
    @form_laboratorio = FormLaboratorio.new
  end

  # GET /form_laboratorios/1/edit
  def edit
  end

  # POST /form_laboratorios
  # POST /form_laboratorios.json
  def create
    @form_laboratorio = FormLaboratorio.new(form_laboratorio_params)

    respond_to do |format|
      if @form_laboratorio.save
        format.html { redirect_to @form_laboratorio, notice: 'Form laboratorio was successfully created.' }
        format.json { render :show, status: :created, location: @form_laboratorio }
      else
        format.html { render :new }
        format.json { render json: @form_laboratorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_laboratorios/1
  # PATCH/PUT /form_laboratorios/1.json
  def update
    respond_to do |format|
      if @form_laboratorio.update(form_laboratorio_params)
        format.html { redirect_to @form_laboratorio, notice: 'Form laboratorio was successfully updated.' }
        format.json { render :show, status: :ok, location: @form_laboratorio }
      else
        format.html { render :edit }
        format.json { render json: @form_laboratorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_laboratorios/1
  # DELETE /form_laboratorios/1.json
  def destroy
    @form_laboratorio.destroy
    respond_to do |format|
      format.html { redirect_to form_laboratorios_url, notice: 'Form laboratorio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form_laboratorio
      @form_laboratorio = FormLaboratorio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_laboratorio_params
      params.require(:form_laboratorio).permit(:nombre, :paciente_id, :usuario_id, :hospital_id, :fecha_toma_muestra, :fecha_entrega)
    end
end

app/helpers/form_laboratorios_helper.rb
module FormLaboratoriosHelper
end

app/views/form_laboratorios/_form.html.erb
<%= simple_form_for(@form_laboratorio) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="form-inputs">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-6">.<%= f.association :paciente %></div>
            <div class="col-xs-6">.<%= f.association :hospital %></div>
          </div>
        </div>
      </div>
    </div>
    <%= f.input :nombre %>

    <%= f.input :fecha_toma_muestra, :label=>"Fecha de toma de muestra" %>
    <%= f.input :fecha_entrega %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/form_laboratorios/edit.html.erb
<h1>Editar Formulario Laboratorio</h1>

<%= render 'form' %>

<%= link_to 'Ver', @form_laboratorio %> |
<%= link_to 'Atras', form_laboratorios_path %>

app/views/form_laboratorios/index.html.erb
<h1>Laboratorios</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Paciente</th>
      <th>Usuario</th>
      <th>Hospital</th>
      <th>Fecha Toma de Muestra</th>
      <th>Fecha de Entrega</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @form_laboratorios.each do |form_laboratorio| %>
      <tr>
        <td><%= form_laboratorio.nombre %></td>
        <td><%= form_laboratorio.paciente %></td>
        <td><%= form_laboratorio.usuario %></td>
        <td><%= form_laboratorio.hospital %></td>
        <td><%= form_laboratorio.fecha_toma_muestra %></td>
        <td><%= form_laboratorio.fecha_entrega %></td>
        <td><%= link_to 'Ver', form_laboratorio %></td>
        <td><%= link_to 'Editar', edit_form_laboratorio_path(form_laboratorio) %></td>
        <td><%= link_to 'Eliminar', form_laboratorio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Formulario Laboratorio', new_form_laboratorio_path, :class=> "btn" %>

app/views/form_laboratorios/new.html.erb
<h1>Nuevo Formulario Laboratorio</h1>

<%= render 'form' %>

<%= link_to 'Atras', form_laboratorios_path %>

app/views/form_laboratorios/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Nombre:</strong>
  <%= @form_laboratorio.nombre %>
</p>

<p>
  <strong>Paciente:</strong>
  <%= @form_laboratorio.paciente %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @form_laboratorio.usuario %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @form_laboratorio.hospital %>
</p>

<p>
  <strong>Fecha Toma de Muestra:</strong>
  <%= @form_laboratorio.fecha_toma_muestra %>
</p>

<p>
  <strong>Fecha de Entrega:</strong>
  <%= @form_laboratorio.fecha_entrega %>
</p>

<%= link_to 'Editar', edit_form_laboratorio_path(@form_laboratorio) %> |
<%= link_to 'Atras', form_laboratorios_path %>