config/routes.rb
Rails.application.routes.draw do

  resources :tuberculoses

  resources :tuberculosis

  get 'reporte/index'
  get 'reporte/pacientes'
  get 'reporte/detalle_insumos_reactivos'
  get 'reporte/insumo_reactivos_pacientes'
  get 'reporte/hospital'

  resources :laboratorios

  resources :personas

  resources :comunidads

  resources :municipios

  resources :line_items

  resources :carts

  get 'registro_insumos_reactivos/index2'

  resources :registro_insumos_reactivos

  resources :baciloscopia_forms

  resources :form_cultivos

  get 'configuraciones/index'

  resources :establecimientos

  resources :sectors

  resources :areas

  resources :distritos

  resources :provincia

  resources :kardexes

  resources :insumo_reactivos

  resources :inventarios

  resources :form_leishmaniases

  resources :form_malaria

  resources :form_chagas

  resources :form_tuberculoses

  resources :form_liquidos

  resources :biopsias_forms

  resources :form_anat_citologicas

  resources :form_cancer_uterinos

  resources :form_laboratorios

  resources :hospitals

  resources :diagnosticos

  resources :pacientes

  resources :rols

  get 'principal/index'

  devise_for :users
  resources :users

  root 'principal#index'

end

app/models/form_cultivo.rb
class FormCultivo < ActiveRecord::Base
  belongs_to :paciente
  belongs_to :hospital

  validates_presence_of :paciente
  validates_presence_of :hospital
end

app/controllers/form_cultivos_controller.rb
class FormCultivosController < ApplicationController
  before_action :set_form_cultivo, only: [:show, :edit, :update, :destroy]

  # GET /form_cultivos
  # GET /form_cultivos.json
  def index
    @form_cultivos = FormCultivo.all
    query = queryGrafico('form_cultivos')
    #query = "SELECT date_trunc('month', created_at) as label, COUNT(*) AS value  FROM form_chagas where form_chagas.created_at>='2016-01-01 00:00:00' and form_chagas.created_at<='2016-12-12 24:00:00' GROUP BY 1 ORDER BY label ASC"
    @reporte_mensual_cultivos = Paciente.find_by_sql(query)
    gon.query = query
    gon.reporte_mensual_cultivos = @reporte_mensual_cultivos
  end

  # GET /form_cultivos/1
  # GET /form_cultivos/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "file_name",
               :layout => 'pdf.html.erb',
               :page_size => 'Letter',
               :footer => {:right => '[page] de [topage]', :font_size => 7}
      end
    end
  end

  # GET /form_cultivos/new
  def new
    @form_cultivo = FormCultivo.new
  end

  # GET /form_cultivos/1/edit
  def edit
  end

  # POST /form_cultivos
  # POST /form_cultivos.json
  def create
    @form_cultivo = FormCultivo.new(form_cultivo_params)
    begin
      @paciente = Paciente.find(params[:form_cultivo][:paciente_id])
      @paciente.form_laboratorio_id=10
      @paciente.save
    rescue Exception => e

    end

    respond_to do |format|
      if @form_cultivo.save
        format.html { redirect_to @form_cultivo, notice: 'Form cultivo was successfully created.' }
        format.json { render :show, status: :created, location: @form_cultivo }
      else
        format.html { render :new }
        format.json { render json: @form_cultivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_cultivos/1
  # PATCH/PUT /form_cultivos/1.json
  def update
    respond_to do |format|
      if @form_cultivo.update(form_cultivo_params)
        format.html { redirect_to @form_cultivo, notice: 'Form cultivo was successfully updated.' }
        format.json { render :show, status: :ok, location: @form_cultivo }
      else
        format.html { render :edit }
        format.json { render json: @form_cultivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_cultivos/1
  # DELETE /form_cultivos/1.json
  def destroy
    @form_cultivo.destroy
    respond_to do |format|
      format.html { redirect_to form_cultivos_url, notice: 'Form cultivo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form_cultivo
      @form_cultivo = FormCultivo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_cultivo_params
      params.require(:form_cultivo).permit(:paciente_id, :hospital_id, :fecha, :tipo_muestra, :medico, :periodo, :observaciones)
    end
end

app/helpers/form_cultivos_helper.rb
module FormCultivosHelper
end

app/views/form_cultivos/_form.html.erb
<% fecha=Time.now %>
<%= simple_form_for(@form_cultivo) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <div class="panel panel-default">
        <div class="panel-body">

          <div class="col-xs-6">
          <%= f.association :paciente,label_method: :nombres %></div>
          <div class="col-xs-6">
            <%= f.association :hospital, label_method: :nombre, :as => :collection_select, collection: Hospital.where("nombre<>'Todos'"), :label => "Hospital" %>
          </div>
        </div>
      </div>
    </div>

    <div class="form-inputs">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-4">
               <div class="input-group">
                    <b>Fecha</b>
                      <input class="form-control hasDatepicker" id="paciente_fecha_nacimiento" name="form_cultivo[fecha]" type="date" max='<%= fecha.strftime("%Y") + "-" + fecha.strftime("%m") + "-" + fecha.strftime("%d") %>' min="1866-01-01"
                      value='<%= fecha.strftime("%Y") + "-" + fecha.strftime("%m") + "-" + fecha.strftime("%d") %>'>
                      <div class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                      </div>
                  </div>
              <!-- 
              <%= f.input :fecha do %>
              <div class="input-group">
                <%= f.text_field :fecha, :class => 'form-control' %>
                <div class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </div>
              </div>
              <%end%>
              -->


            </div>
            <div class="col-sm-4">
              <%= f.input :tipo_muestra %>
            </div>
            <div class="col-sm-4">

            <div class="input-group">
                    <b>Fecha</b>
                      <input class="form-control hasDatepicker" id="paciente_fecha_nacimiento" name="form_cultivo[periodo]" type="date" max='<%= fecha.strftime("%Y") + "-" + fecha.strftime("%m") + "-" + fecha.strftime("%d") %>' min="1866-01-01"
                      value='<%= fecha.strftime("%Y") + "-" + fecha.strftime("%m") + "-" + fecha.strftime("%d") %>'>
                      <div class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                      </div>
                  </div>
            <!--
              <%= f.input :periodo do %>
              <div class="input-group">
                <%= f.text_field :periodo, :class => 'form-control' %>
                <div class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </div>
              </div>
             <% end %>
            -->

             </div>
            <div class="col-sm-4">
             <%= f.input :observaciones %>
            </div>
            <div class="col-sm-4">
            <%= f.input :medico %>
            </div>
          </div>
        </div>
      </div>
    </div>



<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>
</div>

<script>
    var ready;

    ready = function () {
        $("#form_cultivo_fecha, #form_cultivo_periodo").datepicker({
            yearRange: "-100:+0",
            changeMonth: true,
            changeYear: true
        });
        $('[data-toggle="tooltip"]').tooltip();
        $('[data-toggle="popover"]').popover();
    };

    $(document).ready(ready);
    $(document).on('page:load', ready);
</script>

app/views/form_cultivos/edit.html.erb
<h1>Cultivos</h1>

<%= render 'form' %>

<%= link_to 'Ver', @form_cultivo %> |
<%= link_to 'Editar', form_cultivos_path %>

app/views/form_cultivos/index.html.erb
<h1>Cultivos</h1>

<table class="table table-striped table-hover" id="tabla">
  <thead>
    <tr>
      <th>Paciente</th>
      <th>Hospital</th>
      <th>Fecha</th>
      <th>Tipo muestra</th>
      <th>Medico</th>
      <th>Periodo</th>
      <th>Observaciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @form_cultivos.each do |form_cultivo| %>
      <tr>
        <td><%= form_cultivo.paciente.nombres %></td>
        <td><%= form_cultivo.hospital %></td>
        <td><%= form_cultivo.fecha %></td>
        <td><%= form_cultivo.tipo_muestra %></td>
        <td><%= form_cultivo.medico %></td>
        <td><%= form_cultivo.periodo %></td>
        <td><%= form_cultivo.observaciones %></td>
        <td><%= link_to 'Ver', form_cultivo %></td>
        <td><%= link_to 'Editar', edit_form_cultivo_path(form_cultivo) %></td>
        <td><%= link_to 'Eliminar', form_cultivo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
          <%= link_to '<i class="glyphicon glyphicon-list-alt"></i>'.html_safe, {:format => "pdf", :controller => "form_cultivos", action: "show", :id => form_cultivo}, :"data-toggle" => "tooltip", :"data-placement" => "bottom", :title => "Crear  Informe", :target => "_blank" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Cultivo', new_form_cultivo_path, :class=> "btn" %>

<a href="javascript:location.reload()">Mostrar historial de registro</a>

<div id="chart-container"></div>
<script type="text/javascript">
  console.log(gon.query);
</script>
<script type="text/javascript">
  FusionCharts.ready(grafico_columna("chart-container","Historial de registro del ultimo año Cultivos","Meses","Cantidad de pacientes registrados",gon.reporte_mensual_cultivos));
</script>

app/views/form_cultivos/new.html.erb
<h1>Cultivos</h1>

<%= render 'form' %>

<%= link_to 'Atras', form_cultivos_path %>

app/views/form_cultivos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="pull-left" style="width: 10%;display: inline-block">
  <%= image_tag "bolivia_escudo.png", :width => '75' %>
</div>
<div style="width: 70%;;display: inline-block" class="text-center">
  <strong>
    SOLICITUD DE ANALISIS CULTIVOS<br/>
    MINISTERIO DE SALUD Y DEPORTES<br/>
    HONORABLE GOBIERNO MUNICIPAL DE POTOSI<br/>
    SERVICIO DEPARTAMENTAL DE SALUD<br/>
  </strong>
</div>
<div class="pull-right" style="width: 15%;;display: inline-block">
  <%= image_tag "potosi_escudo.gif", :width => '50' %>
</div>


<br><br><br>
<table class="table table-condensed">
  <tbody>
  <tr>
    <td><strong>Paciente:</strong> <%= @form_cultivo.paciente.nombres %></td>
    <td><strong>Hospital:</strong> <%= @form_cultivo.hospital %></td>
    <td colspan="2"><strong>Fecha:</strong> <%= @form_cultivo.fecha %></td>
  </tr>
  <tr>
    <td><strong>Tipo de Muestra:</strong> <%= @form_cultivo.tipo_muestra %></td>
    <td colspan="2">Medico:   <%= @form_cultivo.medico %></td>
  </tr>
  <tr>
    <td colspan="2"><strong>Periodo: <%= @form_cultivo.periodo %></td>
     </tr>
  <tr>
    <td><strong>Observaciones: <%= @form_cultivo.observaciones %></td>
     </tr>
  </tbody>
</table>

<%= link_to 'Editar', edit_form_cultivo_path(@form_cultivo) %> |
<%= link_to 'Atras', form_cultivos_path %>

app/views/form_cultivos/show.pdf.erb
<!--
<div class="pull-left" style="width: 10%;display: inline-block">
  <%= wicked_pdf_image_tag "bolivia_escudo.png", :width => '75' %>
</div>
<div style="width: 70%;;display: inline-block" class="text-center">
  <strong>
    SOLICITUD DE ANALISIS CULTIVOS<br/>
    MINISTERIO DE SALUD Y DEPORTES<br/>
    HONORABLE GOBIERNO MUNICIPAL DE POTOSI<br/>
    SERVICIO DEPARTAMENTAL DE SALUD<br/>
  </strong>
</div>
<div class="pull-right" style="width: 15%;;display: inline-block">
  <%= wicked_pdf_image_tag "potosi_escudo.gif", :width => '50' %>
</div>
-->

<p id="notice"><%= notice %></p>
<div class="div-izq">
  <%= wicked_pdf_image_tag "bolivia_escudo.png", :width => '75' %>      
</div>
<div style="width: 400px;display:inline-block">
  <strong style="text-align: center;"> 
         <p>  
            <strong>
              SOLICITUD DE ANALISIS CULTIVOS<br/>
              MINISTERIO DE SALUD Y DEPORTES<br/>
              HONORABLE GOBIERNO MUNICIPAL DE POTOSI<br/>
              SERVICIO DEPARTAMENTAL DE SALUD<br/>
            </strong>
         </p>
  </strong>
</div>
<div class="div-der">
  <%= wicked_pdf_image_tag "potosi_escudo.gif", :width => '50' %>
</div>
<br>
<br><br>


<table class="table table-condensed">
  <tbody>
  <tr>
    <td><strong>Paciente:</strong> <%= @form_cultivo.paciente.nombres %><%= " " %><%= @form_cultivo.paciente.apellidos %></td>
    <td><strong>Hospital:</strong> <%= @form_cultivo.hospital %></td>
    <td colspan="2"><strong>Fecha:</strong> <%= @form_cultivo.fecha %></td>
  </tr>
  <tr>
    <td><strong>Tipo de Muestra:</strong> <%= @form_cultivo.tipo_muestra %></td>
    <td colspan="2"><strong>Medico:</strong>   <%= @form_cultivo.medico %></td>
  </tr>
  <tr>
    <td colspan="2"><strong>Periodo:</strong> <%= @form_cultivo.periodo %></td>
  </tr>
  <tr>
    <td><strong>Observaciones:</strong> <%= @form_cultivo.observaciones %></td>
  </tr>
  </tbody>
</table>